//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealEstateWebsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Post_Image
    {
        public int Image_ID { get; set; }
        public string url { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
    
        public virtual Post Post { get; set; }
    }
}
