//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealEstateWebsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Promotion_Detail
    {
        public int Promotion_ID { get; set; }
        public int Post_ID { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
    
        public virtual Promotion Promotion { get; set; }
        public virtual Post Post { get; set; }
    }
}
